
export const ACTIONS = {
    SET_TRIVIOO_GAME: 'SET_TRIVIOO_GAME',
    CHANGE_GAMER_STATE: 'CHANGE_GAMER_STATE',
    UPDATE_STATUS_PLAYER: 'UPDATE_STATUS_PLAYER',
    SET_GAME_QUESTIONS: 'SET_GAME_QUESTIONS',
    SET_CURRENT_QUESTION_INDEX: 'SET_CURRENT_QUESTION_INDEX',
    SET_RAUND_ANSWERS: 'SET_RAUND_ANSWERS',
    SET_GAME_RESULT: 'SET_GAME_RESULT',
    SET_GAMEMATCH_ID: 'SET_GAMEMATCH_ID'
}