# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
#xcode_select "/Applications/Xcode12.4.app"
platform :ios do
  desc "build a Release"
  lane :beta do
    create_keychain(
      name: "#{ENV["CI_KEYCHAIN_NAME"]}",
      password: "#{ENV["CI_KEYCHAIN_PASSWORD"]}",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    match(
      type: "appstore",
      git_url: "#{ENV["GIT_REPO_URL"]}",
      keychain_name: "#{ENV["CI_KEYCHAIN_NAME"]}",
      keychain_password: "#{ENV["CI_KEYCHAIN_PASSWORD"]}",
      api_key_path: "Authkey.json"
    )
    increment_build_number(xcodeproj: "./ios/mobile.xcodeproj") 
    build_app(workspace: "./ios/mobile.xcworkspace", scheme: "mobile")
    upload_to_testflight(api_key_path: "Authkey.json", skip_waiting_for_build_processing: true)
  end
end
