export const ACTIONS = {
    CONECT_GAMEMATCH: "CONECT_GAMEMATCH",
    CHANGE_GAMER_STATE: "CHANGE_GAMER_STATE",
    UPDATE_STATUS_PLAYER: "UPDATE_STATUS_PLAYER",
    REPLY_QUESTION: "REPLY_QUESTION",
    READY_FOR_NEXT_RAUND: 'READY_FOR_NEXT_RAUND'
}

export const EVENTS = {
    INIT_GAMEMATCH_SETTINGS_FOR_PLAY: 'INIT_GAMEMATCH_SETTINGS_FOR_PLAY',
    UPDATE_ROOM : 'UPDATE_ROOM',
    ERROR: 'ERROR',
    DISCONNECT: 'DISCONNECT',
    GAMER_CHANGE_READY: "GAMER_CHANGE_READY",
    UPTADE_STATUS_PLAYER: "UPTADE_STATUS_PLAYER",
    STAR_GAME: 'STAR_GAME',
    RAUND_RESULT: 'RAUND_RESULT',
    NEXT_RAUND: 'NEXT_RAUND',
    GAME_RESULT: 'GAME_RESULT'
}

export const VIEWS = {
    ROOM: "ROOM",
    QUESTION: "QUESTION",
    RESULTS: "RESULTS",
}